
# Start up SAMWeb, Nginx, SAM Station, and Apache
#

version: "3.7"
services:
    sam_dev_db:
        image:
            sam_dev_db
        environment:
            POSTGRES_USER: samdbs
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: sam_bjwhite

    # Web server/reverse proxy/SSL termination
    apache:
        container_name: nginx
        image: sam-nginx-server
        ports:
            - "127.0.0.1:8483:8483"
            - "127.0.0.1:8480:8480"
        depends_on:
            - samweb_server
            - sam_station
        volumes:
            - type: bind
              source: ./sam_nginx_server/cert/server.crt
              target: /opt/sam/nginx/certs/server.crt
            - type: bind
              source: ./sam_nginx_server/cert/server.key
              target: /opt/sam/nginx/certs/server.key
            - osg-ca-volume:/etc/grid-security/certificates

# SAM Main Services
    #SAM Web Server with DB password as a secret
    samweb-server:
        container_name: samweb-server
        image: samweb-server
        depends_on:
            - osg_authentication
            - sam_dev_db
        environment:
            - EXPERIMENT=sam_bjwhite
            - DB_DATABASE=sam_bjwhite
            - DB_HOST=sam_dev_db
            - DB_PORT=5432
        volumes:
            - type: bind
              source: ./samweb_server/sam-web 
              target: /opt/sam/samweb_server/sam-web

        secrets:
            - samweb_db_secret


    # SAM Station
    sam-station:
        container_name: sam-station
        image: sam-station
        depends_on:
            - osg_authentication
            - samweb_server
        environment:
            - STATION_CLIENT_URL=samdev.fnal.gov
        volumes:
            - type: bind
              source: ./sam_station/sam-station
              target: /opt/sam/sam_station/sam-station
            - type: bind
              source: ./sam_nginx_server/cert/server.crt
              target: /opt/sam/sam_station/server.crt
            - type: bind
              source: ./sam_nginx_server/cert/server.key
              target: /opt/sam/sam_station/server.key
            - ./sam_station/config/bjwhite_test_config.conf:/opt/sam/sam_station/sam_station_config.conf
            - ./sam_station/config/bjwhite_test_file_schema_mapping.json:/opt/sam/sam_station/file_schema_mapping.json
            - ./sam_station/config/bjwhite_test_location_map.yaml:/opt/sam/sam_station/location_map.yaml
              

    # Service to handle OSG CA Certificates by updating them and making them available via the named volume 'osg-ca-volume'
    osg_authentication:
        image: docker.io/bjwhitefnal/grid-security-files:32
        command: ["/bin/bash", "-c", "chmod 755 /out/ && cp -rv --preserve=links /grid-certificates/* /out/"]
        volumes:
            - osg-ca-volume:/out/

# SAM Monitoring Services
    # sam station monitor application server
    #sam_station_monitor:
    #    image: sam-station-monitor
    #    volumes:
    #        - type: bind
    #          source: ./sam_monitoring/sam_station_monitor
    #          target: /opt/sam/sam-station-monitor

    ## SAM Station Monitor Application Server
    #sam_landscape_stats:
    #    image: sam-landscape-stats
    #    volumes:
    #        - type: bind
    #          source: ./sam_monitoring/sam_landscape_stats/sam_stats_graphite.py
    #          target: /sam_stats_graphite.py
    #        - type: bind
    #          source: ./sam_monitoring/sam_landscape_stats/db_read_password
    #          target: /db_read_password
    #    environment:
    #        - GRAPHITE_SERVER_HOST=fifemondata.fnal.gov
    #        - GRAPHITE_SERVER_PORT=2004
    #        - SAMDBS_PASSWORD_FILE=file:db_read_password

    
volumes:
    osg-ca-volume:
    
secrets:
    samweb_db_secret:
        file: ./samweb_server/config/secret/postgres.secret
