# Dockerfile for the SAM Nginx Server

FROM docker.io/library/nginx:1.25.4

#RUN apt-get update -y && apt-get install -y net-tools
#COPY mime.types /etc/mime.types
#COPY config/conf/httpd.conf /usr/local/apache2/conf/httpd.conf
#COPY config/conf.d /usr/local/apache2/conf.d
RUN rm /etc/nginx/conf.d/* /etc/nginx/nginx.conf
COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY ./ngx_gridproxy_module.so /etc/nginx/modules/ngx_gridproxy_module.so


# Make /opt/sam/html DocumentRoot
#RUN mkdir -p /opt/sam/html
# Make the run dir because it doesnt exist otherwise?
#RUN mkdir -p /usr/local/apache2/run

EXPOSE 8483
EXPOSE 8480

# Base image CMD will run nginx "daemon off"